### ISSUE TITLE
Not completely RFC2822 conform

### ISSUE THREAD

**Issue by Skeeve** [book/DateTime-Format-Mail#3]
Hi!

I'm testing Date headers with your module and it fails with this header 

    Date: Wed, 10 Jul 2019 11:20:02 +0200 (CEST)

At first I thought that the format is really not conform, but in fact it is as "(CEST)" simply is a comment, which seems to be allowed by `CFWS`

    date-time       =       [ day-of-week "," ] date FWS time [CFWS]

**Comment by choroba** [comment]
What do you mean? I tried adding

    Wed, 10 Jul 2019 11:20:02 +0200 (CEST)

into the `t/sample_dates` and the test still passes.

**Comment by Skeeve** [comment]
I can recall that the script I wrote failed with exactly that string. Currently I'm removing the comment manually in order to parse using your module.

I will go and check again.

**Comment by Skeeve** [comment]
So this is what I just tested:

```
perl -MDateTime::Format::Mail -MData::Dumper -e '
  $x=DateTime::Format::Mail->new->strict->parse_datetime("Wed, 10 Jul 2019 11:20:02 +0200 (CEST");
  print Dumper $x;
' 
```

Result is `Invalid format for date! at -e line 2.`

**Comment by choroba** [comment]
It's missing the closing parenthesis `)`, but after fixing it, it still only passes the loose translation.

**Comment by Skeeve** [comment]
The parenthesis was a copy&paste error. Sorry for that.

So you're saying it's my misunderstanding and that this format isn't really RFC conform but just an allowed format?

If so, I think we can close the issue and I have to adjust my script.

Thanks for your effort and for explaining.

**Comment by Skeeve** [comment]
Just realised (RFC2822):

> Appendix B. Differences from earlier standards
> This appendix contains a list of changes that have been made in the
> Internet Message Format from earlier standards, specifically [RFC822]
> […]
>   14. Free insertion of comments not allowed in date.*

**Comment by pali** [comment]
RFC5322 4. Obsolete Syntax: https://tools.ietf.org/html/rfc5322#section-4
> Though these syntactic forms MUST NOT be generated according to the grammar in section 3, they MUST be accepted and parsed by a conformant receiver.

RFC5322 4.3. Obsolete Date and Time: https://tools.ietf.org/html/rfc5322#section-4.3
> It also permits comments and folding white space between many of the tokens.


So when parsing Date header you need to allow input which contains comments or folding whitespaces.
